---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: discovery-service
    name: discovery-service
    namespace: fireapp
spec:
    ports:
        - name: "http"
          port: 8761
          targetPort: 8761
    selector:
        app: discovery-service
status:
    loadBalancer: {}
